spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wxhelper?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    platform: mysql
    initialSize: 1
    minIdle: 3
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,slf4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  profiles:
    active: dev
  http:
    encoding:
      charset: UTF-8
      enabled: true
  servlet:
    multipart:
      max-file-size: 100MB
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.edu.cqupt.nmid.wxhelper.wxhelper.po
  config-location: classpath:mybatis-config.xml
server:
  tomcat:
    accesslog:
      encoding: UTF-8
    uri-encoding: UTF-8
config:
  jwt:
    # 加密密钥
    secret: A0B1C2D3E4F5G6H7I8J9KALBMCNDOEPFQ0R1S2T3U4V5W6X7Y8Z9
    # token有效时长
    expire: 3600
    #header 名称
    header: token
  cos:
    secretId: AKIDvjNo45SHVYNyMaqIqFSRDm9HDxTocHjy
    secretKey:
    regin: ap-chengdu
    url: https://wxhelper-1300698904.cos.ap-chengdu.myqcloud.com/
    bucketName: wxhelper-1300698904

#文件存储及访问
myproperties:
  file-save-location: /usr/local/src/wxhelper/images/
  file-visit-url: https://wxhelper.itrover.cn/wxhelper/images/
pagehelper:
  reasonable: true

---
spring:
  profiles: dev
server:
  port: 8081
logging:
  level:
   root: info
   cn.edu.cqupt.nmid.wxhelper.wxhelper: info
  file:
    name: wxhelper-log/wxhelper-dev.log
    clean-history-on-start: true

---
spring:
  profiles: pro
server:
  port: 8080
logging:
  level:
    root: error
    cn.edu.cqupt.nmid.wxhelper.wxhelper: error
  file:
    clean-history-on-start: true
    name: wxhelper-log/wxhelper-pro.log
debug: false

